#!/usr/bin/env bash
set -euo pipefail

# Requires pspdev toolchain: https://github.com/pspdev/pspdev
# and cargo-psp: cargo install cargo-psp
: "${PSPDEV:=/usr/local/pspdev}"
export PATH="${PSPDEV}/bin:${PATH}"
export RUSTFLAGS="${RUSTFLAGS:-} -Zthreads=16"

cargo psp --release "$@"

PRXDIR=target/mipsel-sony-psp/release
echo "Output: ${PRXDIR}/ruffle4consoles.prx"
echo ""
echo "Deploy to ms0:/PSP/GAME/ruffle/ with:"
echo "  EBOOT.PBP   <- generated by cargo-psp"
echo "  movie.swf   <- your SWF file"
